config/routes.rb
Rails.application.routes.draw do
  resources :polls

  root 'polls#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poll.rb
class Poll < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def index
    @polls = Poll.all.order("created_at DESC")
  end

  def show
  end

  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.new(poll_params)
    if @poll.save
      redirect_to @poll, notice: "Poll launched Successfully!"
    else
      render 'new'
    end
  end

  private
  def poll_params
    params.require(:poll).permit(:question)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Polar
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
%body
  - flash.each do |name, msg|
    = content_tag :div, msg
  = yield

app/views/polls/_form.html.haml
= simple_form_for @poll do |f|
  = f.error_messages
  = f.input :name
  -# = f.input :price, :hint => "prices should be in USD"
  -# = f.input :released_on
  -# = f.association :category, :include_blank => false
  -# = f.input :rating, :collection => 1..5, :as => :radio
  -# = f.input :discontinued
  = f.button :submit

app/views/polls/flow.html.haml
%h1 Hello, Pollers!

= link_to "New Poll", new_poll_path
-@polls.each do |poll|
  = poll.question

app/views/polls/index.html.haml
%h1 Hello, Pollers!

= link_to "New Poll", new_poll_path
-@polls.each do |poll|
  = poll.question

app/views/polls/new.html.haml
%h1 New Form

= simple_form_for @poll do |f|
  -# = f.error_messages
  = f.input :question
  -# = f.input :price, :hint => "prices should be in USD"
  -# = f.input :released_on
  -# = f.association :category, :include_blank => false
  -# = f.input :rating, :collection => 1..5, :as => :radio
  -# = f.input :discontinued
  = f.button :submit

= link_to "Back", root_path

app/views/polls/show.html.haml
= @poll.question
= link_to "Back", root_path